### ISSUE TITLE
Python Plugin / Function Call

### ISSUE THREAD

**Issue by bhairavmehta95** [neka-nat/gazebo_domain_randomization#1]
Hi @neka-nat , this looks fantastic.

I am looking to incorporate this into my own work, but I was wondering how your code actually gets triggered? Is there a way to only change the lights / colors by calling a function / service? 

For context, I am using an RL set up, and am looking to only call this function after the reset of each environment.

**Comment by neka-nat** [comment]
Hi @bhairavmehta95.
I think the best way is executing following command.

```
roslaunch gazebo_domain_randomizer domain_randomizer.launch
```

However, since the shape_randomizer is still unstable, it is better to execute only light_randomizer.

```
rosrun gazebo_domain_randomizer light_randomizer
```

**Comment by neka-nat** [comment]
By publishing a topic named "trigger", it executes randomizing function.
Please see README.md and try using it.
